add permissions

diff --git a/0x07-networking_basics/5-is_the_host_on_the_network b/0x07-networking_basics/5-is_the_host_on_the_network
--- a/0x07-networking_basics/5-is_the_host_on_the_network
+++ b/0x07-networking_basics/5-is_the_host_on_the_network
@@ -1,1 +1,16 @@
 #!/usr/bin/env bash
+# Check if an argument is provided
+if [ $# -eq 0 ]; then
+echo "Usage: $0 {IP_ADRESS}"
+exit 1
+fi
+
+# Extract IP address m the command-line argument
+ip_address=$1
+
+# Ping the IP address 5 times
+echo "Pinging $ip_address 5 times..."
+ping -c 5 $ip_address
+
+# Exit with the ping command's exit code
+exit $?
